
// Sample data with realistic timestamps
import 'package:flutter/material.dart';
import 'package:twedrli/Pages/home.dart';

final ValueNotifier<List<LostFoundItem>> allItemsNotifier = ValueNotifier([
  LostFoundItem(
    id: '1',
    title: 'Blue Hydro Flask',
    location: 'Chemistry Building, Lab 2',
    timestamp: DateTime.now().subtract(const Duration(hours: 2)),
    status: ItemStatus.lost,
    imagePath: 'assets/Bottle.png',
    description: 'Blue 32oz Hydro Flask with stickers',
    contactInfo: 'Contact: lostandfound@uni.edu',
    color: 'Blue',
    category: 'Water Bottle',
  ),
  LostFoundItem(
    id: '2',
    title: 'TI-84 Calculator',
    location: 'Main Library - 3rd Floor',
    timestamp: DateTime.now().subtract(const Duration(hours: 5)),
    status: ItemStatus.found,
    imagePath: 'assets/calc.png',
    description: 'Texas Instruments TI-84 Plus',
    contactInfo: 'Claim at library front desk',
    color: 'Grey',
    category: 'Calculator',
  ),
  LostFoundItem(
    id: '3',
    title: 'Car Keys & Keychain',
    location: 'Student Union Cafe',
    timestamp: DateTime.now().subtract(const Duration(days: 1)),
    status: ItemStatus.claimed,
    imagePath: 'assets/keys.png',
    description: 'Honda key with blue keychain',
    contactInfo: 'Claimed by Mohamed A.',
    color: 'Black'  ,
    category: 'Keys',

  ),
  LostFoundItem(
    id: '4',
    title: 'MacBook Pro Charger',
    location: 'Engineering Building',
    timestamp: DateTime.now().subtract(const Duration(hours: 3)),
    status: ItemStatus.found,
    imagePath: 'assets/charger.png',
    description: 'Apple 61W USB-C Charger',
    contactInfo: 'Available at security desk',
    color: 'White',
    category: 'Charger',
  ),
  LostFoundItem(
    id: '5',
    title: 'Wireless Headphones',
    location: 'Student Gym',
    timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
    status: ItemStatus.lost,
    imagePath: 'assets/headphones.png',
    description: 'Black Sony WH-1000XM4',
    contactInfo: 'Contact: fitnesscenter@uni.edu',
    color: 'Black',
    category: 'Headphones',
  ),
  LostFoundItem(
    id: '6',
    title: 'Black Umbrella',
    location: 'Bus Stop near Dorms',
    timestamp: DateTime.now().subtract(const Duration(days: 2)),
    status: ItemStatus.found,
    imagePath: 'assets/umbrella.png',
    description: 'Black umbrella with wooden handle',
    contactInfo: 'Claim at campus security',
    color: 'Black',
    category: 'Umbrella',
  )
    ,  LostFoundItem(
      id: '8',
      title: 'Samsung Earbuds Pro',
      location: 'Faculty of Computer Science',
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
      status: ItemStatus.lost,
      imagePath: 'assets/se.png',
      description: 'Samsung Galaxy Buds Pro in black',
      contactInfo: 'Contact: cs.faculty@uni.edu',
      color: 'Black',
      category: 'Earbuds',
    ),
    LostFoundItem(
      id: '9',
      title: 'iPhone 13',
      location: 'University Restaurant (RU)',
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
      status: ItemStatus.found,
      imagePath: 'assets/iphone.png',
      description: 'iPhone 13 with blue case',
      contactInfo: 'Contact: restaurant@uni.edu',
      color: 'Blue',
      category: 'Phone',
    ),
    LostFoundItem(
      id: '10',
      title: 'Student ID Card',
      location: 'Faculty of Medicine',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      status: ItemStatus.lost,
      imagePath: 'assets/id.png',
      description: 'Student ID card - Name: John Doe',
      contactInfo: 'Contact: security@uni.edu',
      color: 'White',
      category: 'Student ID Card',
    ),
]);


final List<String> objectTypes = [
  "Phone",
  "Laptop",
  "Tablet",
  "Smart Watch",
  "Headphones",
  "Earbuds",
  "AirPods",
  "Charger",
  "Power Bank",
  "USB Flash Drive",
  "External Hard Drive",
  "Calculator",
  "Graphing Calculator",
  "Wallet",
  "Purse",
  "Backpack",
  "Handbag",
  "Student ID Card",
  "National ID Card",
  "Passport",
  "Driver’s License",
  "Car Keys",
  "House Keys",
  "Locker Key",
  "Notebook",
  "Binder",
  "Textbook",
  "Lab Manual",
  "Folder",
  "Pen",
  "Pencil Case",
  "Glasses",
  "Sunglasses",
  "Water Bottle",
  "Lunch Box",
  "Jacket",
  "Sweater",
  "Hoodie",
  "Scarf",
  "Umbrella",
  "USB Cable",
  "Mouse",
  "Keyboard",
  "Scientific Instrument",
  "Lab Coat",
  "Access Card",
  "Sports Equipment",
  "Football",
  "Gym Bag",
  "Bluetooth Speaker",
  "Camera",
  "Microphone",
  "Tripod",
  "Project Report",
  "Presentation Clicker",
  "Diary",
  "Makeup Bag",
  "Medication",
];

final List<String> campusZones = [
  "Faculté des Sciences",
  "Faculté des lettres et des langues",
  "Faculté des sciences humaines et sociales",
 "Faculté des Sciences Islamiques",
 "Departement de biologie ",
  "Departement de langue arabe et des Arts",
 "Departement de psychologie",
 "Departement de philosphie",
 "Departement d'histoire ",
 "Fablab Univeristé de Tlemcen",
  "Bibliothéque centrale",
"Centre D'enseingnement intensif des langues CEIL",
 "Le restaurant",
  "Résidence Universitaire Mansourah 5",
  "Résidence Universitaire Martyre Maliha Hamidou Mansourah",
"Résidence Universitaire Ben Ahmed abel kader Mansourah 7",
"Résidence Universitaire Ahmed Mohammed Mansourah 4",
];



final List<String> departements = [
  "Departement de biologie",
  "Departement de langue arabe et des Arts",
  "Departement de psychologie",
  "Departement de philosophie",
  "Departement d'histoire",
];

final ValueNotifier<List<LostFoundItem>> savedItemsNotifier = ValueNotifier([]);

