// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmBp27-MpG5Y09wq6GY_gGk5Ut1hwVjw',
    appId: '1:1031363753988:web:dfc9fe51856a0ab9c31d51',
    messagingSenderId: '1031363753988',
    projectId: 'xoshka-374e1',
    authDomain: 'xoshka-374e1.firebaseapp.com',
    databaseURL: 'https://xoshka-374e1-default-rtdb.firebaseio.com',
    storageBucket: 'xoshka-374e1.firebasestorage.app',
    measurementId: 'G-GFQC582B85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-d6jB6tcFGclM1nfsV8mStGT-814WQyE',
    appId: '1:1031363753988:android:8b501d27a8b3b46fc31d51',
    messagingSenderId: '1031363753988',
    projectId: 'xoshka-374e1',
    databaseURL: 'https://xoshka-374e1-default-rtdb.firebaseio.com',
    storageBucket: 'xoshka-374e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qy2uRZjGGwIFEVfVikABcUK-PtY76eE',
    appId: '1:1031363753988:ios:91e28f52cf900343c31d51',
    messagingSenderId: '1031363753988',
    projectId: 'xoshka-374e1',
    databaseURL: 'https://xoshka-374e1-default-rtdb.firebaseio.com',
    storageBucket: 'xoshka-374e1.firebasestorage.app',
    iosBundleId: 'com.example.xorussian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qy2uRZjGGwIFEVfVikABcUK-PtY76eE',
    appId: '1:1031363753988:ios:91e28f52cf900343c31d51',
    messagingSenderId: '1031363753988',
    projectId: 'xoshka-374e1',
    databaseURL: 'https://xoshka-374e1-default-rtdb.firebaseio.com',
    storageBucket: 'xoshka-374e1.firebasestorage.app',
    iosBundleId: 'com.example.xorussian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqmBp27-MpG5Y09wq6GY_gGk5Ut1hwVjw',
    appId: '1:1031363753988:web:3acd838dfa62bee5c31d51',
    messagingSenderId: '1031363753988',
    projectId: 'xoshka-374e1',
    authDomain: 'xoshka-374e1.firebaseapp.com',
    databaseURL: 'https://xoshka-374e1-default-rtdb.firebaseio.com',
    storageBucket: 'xoshka-374e1.firebasestorage.app',
    measurementId: 'G-6C78PS1F7G',
  );
}
