// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFibzR-loLf0QPqe_UmEFtdNHfSSKLlk',
    appId: '1:111308177572:web:d060202649346f30126631',
    messagingSenderId: '111308177572',
    projectId: 'mealplanner-e8a0b',
    authDomain: 'mealplanner-e8a0b.firebaseapp.com',
    storageBucket: 'mealplanner-e8a0b.firebasestorage.app',
    measurementId: 'G-SEQ2HYHJ3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUyaAHIDhjuqEdtHgVBwivhcGJm_l5kaQ',
    appId: '1:111308177572:android:6d169eccc0b32f5f126631',
    messagingSenderId: '111308177572',
    projectId: 'mealplanner-e8a0b',
    storageBucket: 'mealplanner-e8a0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtF-yloJVBlltm_nmNyePIo3nPOh_8w2M',
    appId: '1:111308177572:ios:0d8eff209042548e126631',
    messagingSenderId: '111308177572',
    projectId: 'mealplanner-e8a0b',
    storageBucket: 'mealplanner-e8a0b.firebasestorage.app',
    iosBundleId: 'com.example.fl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtF-yloJVBlltm_nmNyePIo3nPOh_8w2M',
    appId: '1:111308177572:ios:0d8eff209042548e126631',
    messagingSenderId: '111308177572',
    projectId: 'mealplanner-e8a0b',
    storageBucket: 'mealplanner-e8a0b.firebasestorage.app',
    iosBundleId: 'com.example.fl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFibzR-loLf0QPqe_UmEFtdNHfSSKLlk',
    appId: '1:111308177572:web:daa9c4e619e9fc5c126631',
    messagingSenderId: '111308177572',
    projectId: 'mealplanner-e8a0b',
    authDomain: 'mealplanner-e8a0b.firebaseapp.com',
    storageBucket: 'mealplanner-e8a0b.firebasestorage.app',
    measurementId: 'G-HRS54Y1X7N',
  );
}
