name: twedrli
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  latlong2: ^0.9.1
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  flutter_map: ^8.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Bottle.png
    - assets/calc.png
    - assets/keys.png
    - assets/logo.png
    - assets/charger.png
    - assets/headphones.png
    - assets/bl.png
    - assets/apple.png
    - assets/red.png
    - assets/earbuds.png
    - assets/se.png
    - assets/iphone.png
    - assets/id.png
    - assets/umbrella.png
    - assets/bg.png
    - assets/google.png
    - assets/splash.png
    - assets/logo2.png
    - assets/ttr/
    - assets/ttr/7-Create_post_page.png
